src/main/scala/zio/nio/channels/AsynchronousChannel.scala
The Java NIO API allows arbitrary "attachments" to be passed through to the `CompletionHandler` instance (callback). For ZIO, we only ever need a single internal implementation of
`CompletionHandler`, and this does not need the attachment parameter. Exposing the attachment parameter in the public API serves no purpose.
=> Remove unnecessary attachment parameters.

README.md
=> Change green X's to red X's

src/main/scala/zio/nio/channels/AsynchronousChannel.scala, src/test/scala/zio/nio/ChannelSuite.scala
@mijicd I haven't extracted method you asked because name and signature will be weird probably  similar to this ```def failIfNegativeBytesReturn(nb: Int): IO[IOExcetption, Int]. ```
@quelgar the changes in test you propose are not working - server hangs and never read anything.
=>  #109 detect closed client connection

.circleci/config.yml, website/siteConfig.js
=> Publish microsite

website/core/Footer.js, website/static/css/custom.css
Hi, here are just some last little details that I missed in main microsite PR. 
This is what differs `zio-nio` microsite from `zio` microsite so added these improvements for consistency.
=> Added gitter chat. Corrected footer

docs/essentials/sockets.md, examples/src/main/scala/StreamsBasedServer.scala, src/main/scala/zio/nio/channels/AsynchronousChannel.scala, src/test/scala/zio/nio/channels/ChannelSpec.scala
resolves #107
/cc @iravid @pshemass
=> fix resource leak in AsynchronousServerSocketChannel#accept

nio-core/src/main/scala/zio/nio/core/file/Path.scala, nio-core/src/main/scala/zio/nio/core/file/WatchService.scala, nio-core/src/test/scala/zio/nio/core/channels/FileChannelSpec.scala, nio/src/main/scala/zio/nio/file/FileSystem.scala, nio/src/main/scala/zio/nio/file/Files.scala, nio/src/test/scala/zio/nio/channels/FileChannelSpec.scala
=> separate files/ for nio and nio-core

nio-core/src/main/scala/zio/nio/core/Buffer.scala, nio-core/src/main/scala/zio/nio/core/charset/AutoDetect.scala, nio-core/src/main/scala/zio/nio/core/charset/Charset.scala, nio-core/src/main/scala/zio/nio/core/charset/CharsetDecoder.scala, nio-core/src/main/scala/zio/nio/core/charset/CharsetEncoder.scala, nio-core/src/main/scala/zio/nio/core/charset/CoderResult.scala, nio-core/src/main/scala/zio/nio/core/charset/StreamCodeState.scala, nio-core/src/main/scala/zio/nio/core/charset/package.scala, nio-core/src/test/scala/zio/nio/core/charset/CharsetSpec.scala
Extra features beyond the Java API:
* `Chunk[Char]`/`Chunk[Byte]` encoding/decoding
* stream of Chunks encoding/decoding.
=> ZIO wrappers for java.nio.charset

README.md
Removing section about competition as discussed in #152
=> Remove competition section

build.sbt, examples/src/main/scala/StreamsBasedServer.scala, nio-core/src/main/scala/zio/nio/core/MappedByteBuffer.scala, nio-core/src/main/scala/zio/nio/core/channels/AsynchronousChannel.scala, nio-core/src/main/scala/zio/nio/core/channels/AsynchronousFileChannel.scala, nio-core/src/main/scala/zio/nio/core/channels/FileChannel.scala, nio-core/src/main/scala/zio/nio/core/charset/CharsetDecoder.scala, nio-core/src/main/scala/zio/nio/core/charset/CharsetEncoder.scala, nio-core/src/main/scala/zio/nio/core/file/Path.scala, nio-core/src/main/scala/zio/nio/core/file/WatchService.scala, nio-core/src/test/scala/zio/nio/core/BaseSpec.scala, nio-core/src/test/scala/zio/nio/core/BufferSpec.scala, nio-core/src/test/scala/zio/nio/core/channels/AsynchronousChannelGroupSpec.scala, nio-core/src/test/scala/zio/nio/core/channels/ChannelSpec.scala, nio-core/src/test/scala/zio/nio/core/channels/DatagramChannelSpec.scala, nio-core/src/test/scala/zio/nio/core/channels/FileChannelSpec.scala, nio-core/src/test/scala/zio/nio/core/channels/ScatterGatherChannelSpec.scala, nio-core/src/test/scala/zio/nio/core/channels/SelectorSpec.scala, nio-core/src/test/scala/zio/nio/core/charset/CharsetSpec.scala, nio-core/src/test/scala/zio/nio/core/file/PathSpec.scala, nio/src/main/scala/zio/nio/channels/AsynchronousChannel.scala, nio/src/main/scala/zio/nio/channels/AsynchronousFileChannel.scala, nio/src/main/scala/zio/nio/channels/FileChannel.scala, nio/src/test/scala/zio/nio/BaseSpec.scala, nio/src/test/scala/zio/nio/channels/ChannelSpec.scala, nio/src/test/scala/zio/nio/channels/DatagramChannelSpec.scala, nio/src/test/scala/zio/nio/channels/FileChannelSpec.scala, nio/src/test/scala/zio/nio/channels/ScatterGatherChannelSpec.scala, nio/src/test/scala/zio/nio/channels/SelectorSpec.scala, project/BuildHelper.scala
Closes #163, closes #164
This PR upgrades ZIO to `1.0.0-RC18`. I have created a [follow-up](https://github.com/zio/zio-nio/issues/165) to clean up tests.
=> Upgrade ZIO to RC18

nio-core/src/test/scala/zio/nio/core/channels/ChannelSpec.scala, nio-core/src/test/scala/zio/nio/core/channels/DatagramChannelSpec.scala, nio-core/src/test/scala/zio/nio/core/channels/SelectorSpec.scala, nio/src/test/scala/zio/nio/channels/ChannelSpec.scala, nio/src/test/scala/zio/nio/channels/DatagramChannelSpec.scala, nio/src/test/scala/zio/nio/channels/SelectorSpec.scala
Does the regression test in `zio/nio/channels/ChannelSpec` work properly? Because it seems to fail on master.
@jczuchnowski @quelgar Can I get a review please? Thank you.
=> Use ephemeral ports in tests

README.md, docs/essentials/index.md
Let me know if we should mention something more while we're at it.
=> Update docs to indicate new project structure

nio-core/src/main/scala/zio/nio/core/charset/CharsetDecoder.scala, nio-core/src/main/scala/zio/nio/core/charset/CharsetEncoder.scala, nio-core/src/test/scala/zio/nio/core/charset/CharsetSpec.scala
* Easier to add to a stream expression
* Better error handling
* User no longer needs to deal with chunking
=> Re-implement character set decoding with ZTransducer.

nio/src/main/scala/zio/nio/file/Files.scala
it hit me today with "Too many open files" exception :)
based on java doc
> The returned stream encapsulates a DirectoryStream. If timely disposal of file system resources is required, the try-with-resources construct should be used to ensure that the stream's close method is invoked after the stream operations are completed.
=> close java stream with paths in Files.list

docs/essentials/files.md
When running the code example related to Files I ran into an issue. I wasn't able to write to the file as I had to rights to do so. This PR addresses the issue.
=> Add read and write permissions to opened file

docs/essentials/index.md, nio-core/src/main/scala/zio/nio/core/package.scala, nio-core/src/test/scala/zio/nio/core/channels/ChannelSpec.scala
=> Improve end-of-stream handling.

docs/essentials/sockets.md
=> Update socket docs for latest API.

.github/workflows/ci.yml, .gitignore
=> Prevent issues with Website in CI

.github/workflows/ci.yml, .mergify.yml, project/BuildHelper.scala, project/plugins.sbt
=> Add Java 17 to CI and update build configuration

build.sbt
fixes #439
just repeats #393 on the 2.x branch
=> remove cross version for collection-compat
